name: ci

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        # - https://adoptopenjdk.net
        java-version: [ '11', '16' ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    # - https://github.com/actions/setup-java
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java-version }}

    # - https://github.com/gradle/gradle-build-action
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build
      run: ./gradlew build buildRelease buildFatRelease -x check -x test

    - name: Test
      run: ./gradlew test -x check

    - name: Javadoc & Sources
      run: ./gradlew javadocZip sourcesJar -x check
