name: test-java

on:
  release

jobs:
  test:
    name: Test on ${{ matrix.os }} w/ Java v${{ matrix.version }}
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [1.8]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set Up Java v${{ matrix.version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.version }}
    
    - name: Gradle Test
      run: |
        chmod +x gradlew
        ./gradlew check test
